#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTML-Clean
Version  : 0.8
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/L/LI/LINDNER/HTML-Clean-0.8.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/L/LI/LINDNER/HTML-Clean-0.8.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libh/libhtml-clean-perl/libhtml-clean-perl_0.8-12.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-HTML-Clean-bin
Requires: perl-HTML-Clean-license
Requires: perl-HTML-Clean-man

%description
HTML::Clean - Cleans up HTML code for web browsers, not humans
-------------------------------------------------------------------

%package bin
Summary: bin components for the perl-HTML-Clean package.
Group: Binaries
Requires: perl-HTML-Clean-license
Requires: perl-HTML-Clean-man

%description bin
bin components for the perl-HTML-Clean package.


%package license
Summary: license components for the perl-HTML-Clean package.
Group: Default

%description license
license components for the perl-HTML-Clean package.


%package man
Summary: man components for the perl-HTML-Clean package.
Group: Default

%description man
man components for the perl-HTML-Clean package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n HTML-Clean-0.8
mkdir -p %{_topdir}/BUILD/HTML-Clean-0.8/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/HTML-Clean-0.8/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-HTML-Clean
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-HTML-Clean/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/HTML/Clean.pm
/usr/lib/perl5/site_perl/5.26.1/auto/HTML/Clean/autosplit.ix

%files bin
%defattr(-,root,root,-)
/usr/bin/htmlclean

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-HTML-Clean/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/htmlclean.1
/usr/share/man/man3/HTML::Clean.3
